""" FHIR file reader

reads FHIR bundle JSON files generated by synthea
"""

from __future__ import annotations
from pathlib import Path
from typing import Any
from src.utils.file_manager import FileManager

class FhirFileReader:
    """ Reads FHIR bundle JSON files from disk 
    """
    
    def read_bundle(
        self,
        file_path : str | Path,
    ) -> dict[str, Any]:
        """ Read a FHIR bundle JSON file"""
        
        return FileManager.load_json(Path(file_path))
    
    def extract_resources(
        self,
        bundle : dict[str, Any],
    ) -> list[dict[str, Any]]:
        
        """ Extract resources from fhir bundle"""
        
        entries = bundle.get("entry", [])
        
        resources = [
            entry["resource"]
            for entry in entries
            if "resource" in entry
        ]
        
        return resources
    
    def read_folder(
        self,
        folder : Path,
    ) -> list[dict[str,Any]]:
        
        """ Read all patient bundle file from a folder"""
        
        all_resources = []
        
        for file in folder.glob("*.json"):
            
            #skip metadata exports
            if file.name.startswith("hospitalInformation"):
                continue
            
            if file.name.startswith("practitionerInformation"):
                continue
            
            bundle = self.read_bundle(file)
            
            resources = self.extract_resources(bundle)
            
            all_resources.extend(resources)
            
        return all_resources